version: '3.8'

volumes:
  zabbix-postgres:
  
  

services:
  postgres:
    image: postgres:12.5
    volumes:
      - ./zabbix-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  zabbix:
    
    image: zabbix/zabbix-server-pgsql:ubuntu-5.2.2
    hostname: zabbix
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_VALUECACHESIZE: 64M
      ZBX_CACHESIZE: 128M
      ZBX_TRENDCACHESIZE: 128M
    ports:
      - "10051:10051"
    restart: unless-stopped
    depends_on:
      - postgres

  web:
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-5.2.2
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Europe/Moscow
    ports:
      - "80:8080"
      - "443:8443"
    
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix

